import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StoreWrapper } from "@/components/05_wrappers/store-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreWrapper>
        <body>
          {children}
        </body>
      </StoreWrapper>
    </html>
  );
}
